## 삭제를 원하는 리전 리스트 ##
regions:
  - ap-northeast-2 
  - us-east-1
  - us-east-2
  - us-west-1
  - us-west-2
  - af-south-1
  - ap-east-1
  - ap-south-1
  - ap-northeast-3
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - ap-northeast-1
  - ca-central-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-south-1
  - eu-west-3
  - eu-north-1
  - me-south-1
  - sa-east-1

## produnction ##
account-blacklist:
  - "999999999999"

## AWS 계정 번호 12자리 입력 ##
accounts:
  "123456789012": {}
